manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson

  projects:
    - name: zmk
      remote: petejohanson
      revision: display/bongo-cat-widget
      import: app/west.yml

  self:
    path: config
